{
  "logging_level": -40,
  "client_secure": true,
  "server_secure": false,
  "host_name": "${NODE_HOST}",
  "domain": "${DOMAIN}",
  "label": "easy-nmos-node",
  "how_many": 2,
  "senders": ["v"],
  "receivers": ["v"],
  "http_port": 80,
  "is04_versions": ["v1.3"],
  "is10_versions": ["v1.0"],
  "ca_certificate_file": "/home/certs/ca.pem",
  "authorization_endpoint": "https://${KEYCLOAK_HOST}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth",
  "token_endpoint": "https://${KEYCLOAK_HOST}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token",
  "jwks_uri": "https://${KEYCLOAK_HOST}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs",
  "client_authorization": true,
  "server_authorization": true,
  "authorization_flow": "client_credentials",
  "authorization_scopes": ["registration"],
  "token_endpoint_auth_method": "client_secret_basic"
}
